
tests/run_time/call_stack.c:5:9: runtime error - index 44 out of bounds for type 'int [1]'

dcc explanation: You are using an illegal array index: 44
  Valid indices for an array of size 1 are 0..0
  Make sure the size of your array is correct.
  Make sure your array indices are correct.

Execution stopped here in f3(a=44) in tests/run_time/call_stack.c at line 5:

int f3(int a) {
	int b[] = {0};
-->	return b[a];
}
int f2(int a) {

Values when execution stopped:

a =  <deleted-value>

Function Call Traceback
f3(a=44) called at line 8 of tests/run_time/call_stack.c
f2(a=43) called at line 12 of tests/run_time/call_stack.c
f1(a=42) called at line 16 of tests/run_time/call_stack.c
main()
